name: Eliot Hertenstein
description: I make things on the internet
meta_description: "Eliot Hertenstein is a developer, and journalist, who enjoys trains, photography, and compaining about Java."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://eliothertenstein.com"
google_analytics: "UA-XXXXXXXX-X"
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
permalink: pretty

# Details for the RSS feed generator
url: "https://eliothertenstein.com/posts"
author: "Eliot Hertenstein"
author_description: "I make things on the internet"
# Disqus config
disqus-shortname: ""

# Defaults
defaults:
  - scope:
      path: "" # empty string for all files
      type: posts # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
